source "https://rubygems.org"

gem 'rake', '~> 10.0.3'

group :test do
  gem 'rspec', '~> 2.12.0'
  gem 'em-http-request', '~> 1.0.3'
  gem 'nginx_test_helper', '~> 0.1.0'
  gem 'jshintrb', '~> 0.2.1'
  gem 'therubyracer', '~> 0.11.3'
  gem 'jasmine', '~> 1.3.1'
  gem 'listen', '~> 0.7.2'
  gem 'rb-inotify', '~> 0.8.8'
  gem 'json', '~> 1.7.6'

  gem 'debugger', '~> 1.3.1'
end

group :docs do
  gem 'github-markup', '~> 0.7.5', :require => 'github/markup'
  gem 'RedCloth', '~> 4.2.9'
  gem 'nokogiri', '~> 1.5.6'
end
