source 'http://rubygems.org'

gem 'rake'

group :test do
  gem 'POpen4', '0.1.4'
  gem 'em-http-request', '1.0.3'
  gem 'json', '1.4.3'
  gem 'jasmine', '1.0.2.1'
  gem 'jshintrb'
  gem 'therubyracer'
  gem 'listen'

  platforms :mri_18 do
    gem "ruby-debug"
  end

  platforms :mri_19 do
    gem "ruby-debug19"
  end
end

group :docs do
  gem 'github-markup'
  gem 'RedCloth'
  gem 'nokogiri'
end
