require 'test/unit'
require File.expand_path('test_broadcast_properties', File.dirname(__FILE__))
require File.expand_path('test_channel_statistics', File.dirname(__FILE__))
require File.expand_path('test_cleanup_memory', File.dirname(__FILE__))
require File.expand_path('test_comunication_properties', File.dirname(__FILE__))
require File.expand_path('test_create_many_channels', File.dirname(__FILE__))
require File.expand_path('test_publish_messages', File.dirname(__FILE__))
require File.expand_path('test_publisher', File.dirname(__FILE__))
require File.expand_path('test_setup_parameters', File.dirname(__FILE__))
require File.expand_path('test_subscriber_connection_cleanup', File.dirname(__FILE__))
require File.expand_path('test_subscriber_properties', File.dirname(__FILE__))
require File.expand_path('test_subscriber', File.dirname(__FILE__))
