{{ if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: comet
  labels:
    app: comet
{{ if .Values.ingress.annotations }}
  annotations:
{{ .Values.ingress.annotations . | nindent 4 }}
{{ end }}
spec:
{{ if .Values.ingress.tls }}
  tls:
{{ end }}
  rules:
  - host: {{ tpl .Values.ingress.host $ | quote }}
    http:
      paths:
      - path: /comet
        pathType: Prefix
        backend:
          service:
            name: {{ include "common.names.fullname" . }}
            port:
              number: 80
      - path: /publish
        pathType: Prefix
        backend:
          service:
            name: {{ include "common.names.fullname" . }}
            port:
              number: 80
{{ end }}